apiVersion: certs.k8c.io.certs.k8c.io/v1
kind: Certificate
metadata:
  name: certificate-sample
  namespace: default
spec:
  # the DNS name for which the certificate should be issued
  dnsName: example.k8c.io
  # the time until the certificate expires
  validity: 360d
  # a reference to the Secret object in which the certificate is stored
  secretRef:
    name: my-certificate-secret